### ISSUE TITLE
I hava some error  from riak-java-client

### ISSUE THREAD

**Issue by molele2** [basho/riak#700]
I try execute class from http://docs.basho.com/riak/latest/dev/using/data-types/

import java.net.UnknownHostException;
import java.util.concurrent.ExecutionException;

import com.basho.riak.client.api.RiakClient;
import com.basho.riak.client.api.commands.datatypes.FetchSet;
import com.basho.riak.client.api.commands.datatypes.SetUpdate;
import com.basho.riak.client.api.commands.datatypes.UpdateSet;
import com.basho.riak.client.core.query.Location;
import com.basho.riak.client.core.query.Namespace;
import com.basho.riak.client.core.query.crdt.types.RiakSet;

public class RiakClientSetsTester {

```
/**
 * @param args
 */
public static void main(String[] args) {
    // TODO Auto-generated method stub

    try {

        RiakClient client = RiakClient.newClient("120.24.55.208");

        Location citiesSet =
              new Location(new Namespace("sets", "travel"), "cities");


        FetchSet fetch = new FetchSet.Builder(citiesSet)
            .build();
        FetchSet.Response response = client.execute(fetch);
        RiakSet set = response.getDatatype();
```

//          boolean isEmpty = set.viewAsSet().isEmpty();
            boolean isEmpty = set.view().isEmpty();

```
        SetUpdate su = new SetUpdate()
            .add("Toronto")
            .add("Montreal");
        UpdateSet update = new UpdateSet.Builder(citiesSet, su)
        .build();

        client.execute(update);

        client.shutdown();

    } catch (UnknownHostException e) {
        e.printStackTrace();
    } catch (ExecutionException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    } catch (InterruptedException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
}
```

}

but it run to error : 

java.util.concurrent.ExecutionException: com.basho.riak.client.core.netty.RiakResponseException: Error no bucket type `<<"sets">>`
    at com.basho.riak.client.core.FutureOperation.get(FutureOperation.java:260)
    at com.basho.riak.client.api.commands.CoreFutureAdapter.get(CoreFutureAdapter.java:52)
    at com.basho.riak.client.api.RiakCommand.execute(RiakCommand.java:89)
    at com.basho.riak.client.api.RiakClient.execute(RiakClient.java:293)
    at com.warunion.shop.riak.RiakClientSetsTester.main(RiakClientSetsTester.java:32)
Caused by: com.basho.riak.client.core.netty.RiakResponseException: Error no bucket type `<<"sets">>`
    at com.basho.riak.client.core.netty.RiakResponseHandler.channelRead(RiakResponseHandler.java:53)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Unknown Source)

I want to reduce map from sets and maps 

I don't know show error

**Comment by molele2** [comment]
How to set bucket-type ??????

set? map?  and other?

**Comment by molele2** [comment]
import java.net.UnknownHostException;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.ExecutionException;

import com.basho.riak.client.core.RiakCluster;
import com.basho.riak.client.core.RiakNode;
import com.basho.riak.client.core.operations.SearchOperation;
import com.basho.riak.client.core.util.BinaryValue;

public class RiakClusterClientTester {

```
/**
 * @param args
 */
public static void main(String[] args) {
    // TODO Auto-generated method stub


    try {
        RiakNode.Builder builder = new RiakNode.Builder();
        builder.withMinConnections(10);
        builder.withMaxConnections(50);

        List<String> addresses = new LinkedList<String>();
        addresses.add("120.24.55.208");
```

//          addresses.add("192.168.1.2");
//          addresses.add("192.168.1.3");
            List<RiakNode> nodes = RiakNode.Builder.buildNodes(builder, addresses);
            RiakCluster cluster = new RiakCluster.Builder(nodes).build();
            cluster.start();

```
        String index = "scores";
        String query = "counter:[20 TO *]";
        SearchOperation searchOp = new SearchOperation.Builder(BinaryValue.create(index),query)
            .build();

        cluster.execute(searchOp);
        SearchOperation.Response results = searchOp.get();
        System.out.println("counters::::" + results.getAllResults());
        cluster.shutdown();
    } catch (UnknownHostException | InterruptedException | ExecutionException e) {
        e.printStackTrace();
    }

}
```

}

java.util.concurrent.ExecutionException: com.basho.riak.client.core.netty.RiakResponseException: Unknown message code: 27
    at com.basho.riak.client.core.FutureOperation.get(FutureOperation.java:260)
    at com.warunion.shop.riak.RiakClusterClientTester.main(RiakClusterClientTester.java:41)
Caused by: com.basho.riak.client.core.netty.RiakResponseException: Unknown message code: 27
    at com.basho.riak.client.core.netty.RiakResponseHandler.channelRead(RiakResponseHandler.java:53)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Unknown Source)

**Comment by kesslerm** [comment]
Hi @molele2,

have you followed the instructions in http://docs.basho.com/riak/latest/dev/using/data-types/#Setting-Up-Buckets-to-Use-Riak-Data-Types? You need to set up your CRDT buckets separately from the command line:

```
riak-admin bucket-type create maps '{"props":{"datatype":"map"}}'
riak-admin bucket-type create sets '{"props":{"datatype":"set"}}'
riak-admin bucket-type create counters '{"props":{"datatype":"counter"}}'
```

May I also suggest to use the public riak-users mailing list (http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com) for support questions. The issue tracker is for genuine bugs only.

Hope this helps.

Regards,

Magnus
