### ISSUE TITLE
I hava some error fro counters

### ISSUE THREAD

**Issue by molele2** [basho/riak#701]
package com.warunion.shop.riak;

import java.net.UnknownHostException;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;

import com.basho.riak.client.core.RiakCluster;
import com.basho.riak.client.core.RiakNode;
import com.basho.riak.client.core.operations.SearchOperation;
import com.basho.riak.client.core.util.BinaryValue;

public class RiakClusterClientTester {

```
/**
 * @param args
 */
public static void main(String[] args) {
    // TODO Auto-generated method stub


    try {
        RiakNode.Builder builder = new RiakNode.Builder();
        builder.withMinConnections(10);
        builder.withMaxConnections(50);

        List<String> addresses = new LinkedList<String>();
        addresses.add("120.24.55.208");
```

//          addresses.add("192.168.1.2");
//          addresses.add("192.168.1.3");
            List<RiakNode> nodes = RiakNode.Builder.buildNodes(builder, addresses);
            RiakCluster cluster = new RiakCluster.Builder(nodes).build();
            cluster.start();

```
        String index = "scores";
        String query = "counter:[20 TO *]";
        SearchOperation searchOp = new SearchOperation.Builder(BinaryValue.create(index),query)
            .build();

        cluster.execute(searchOp);
        SearchOperation.Response results = searchOp.get();
        System.out.println("counters::::" + results.getAllResults());
        int numberFound = results.numResults();
        Map<String, List<String>> foundObject = results.getAllResults().get(0);
        String key = foundObject.get("_yz_rk").get(0); // "joan_rivers"
        String bucket = foundObject.get("_yz_rb").get(0); // "people"
        String bucketType = foundObject.get("_yz_rt").get(0); // "counters"


        String index2 = "scores";
        String query2 = "counter:[* TO 15]";
        SearchOperation searchOp2 = new SearchOperation
                .Builder(BinaryValue.create("scores"), "counter:[* TO 15]")
                .build();
        cluster.execute(searchOp);
        SearchOperation.Response results2 = searchOp2.get();


        cluster.shutdown();
    } catch (UnknownHostException | InterruptedException | ExecutionException e) {
        e.printStackTrace();
    }

}
```

}

java.util.concurrent.ExecutionException: com.basho.riak.client.core.netty.RiakResponseException: Unknown message code: 27
    at com.basho.riak.client.core.FutureOperation.get(FutureOperation.java:260)
    at com.warunion.shop.riak.RiakClusterClientTester.main(RiakClusterClientTester.java:42)
Caused by: com.basho.riak.client.core.netty.RiakResponseException: Unknown message code: 27
    at com.basho.riak.client.core.netty.RiakResponseHandler.channelRead(RiakResponseHandler.java:53)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Unknown Source)

**Comment by molele2** [comment]
riak-admin bucket-type update sets '{"props":{"search_index":"hobbies"}}'

import java.net.UnknownHostException;
import java.util.concurrent.ExecutionException;

import com.basho.riak.client.api.RiakClient;
import com.basho.riak.client.api.commands.search.StoreIndex;
import com.basho.riak.client.core.query.Namespace;
import com.basho.riak.client.core.query.search.YokozunaIndex;

public class RiakQuerySets {

```
/**
 * @param args
 */
public static void main(String[] args) {
    // TODO Auto-generated method stub

    String query = "set:football";


    try {
        RiakClient client = RiakClient.newClient("120.24.55.208");
```

//          Namespace peopleBucket = new Namespace("sets", "people");
            YokozunaIndex hobbiesIndex = new YokozunaIndex("hobbies");
            StoreIndex storeIndex =
              new StoreIndex.Builder(hobbiesIndex).build();
            client.execute(storeIndex);

```
        client.shutdown();

    } catch (UnknownHostException e) {
    e.printStackTrace();
    } catch (ExecutionException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
    } catch (InterruptedException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
    }
}
```

}

Caused by: com.basho.riak.client.core.netty.RiakResponseException: Unknown message code: 56
    at com.basho.riak.client.core.netty.RiakResponseHandler.channelRead(RiakResponseHandler.java:53)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Unknown Source)

**Comment by molele2** [comment]
import com.basho.riak.client.FetchMeta;
import com.basho.riak.client.StoreMeta;
import com.basho.riak.client.convert.Converter;
import com.basho.riak.client.convert.PassThroughConverter;
import com.basho.riak.client.core.RiakCluster;
import com.basho.riak.client.core.RiakNode;
import com.basho.riak.client.core.operations.DeleteOperation;
import com.basho.riak.client.core.operations.FetchOperation;
import com.basho.riak.client.core.operations.StoreOperation;
import com.basho.riak.client.query.RiakObject;
import com.basho.riak.client.util.ByteArrayWrapper;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import java.net.UnknownHostException;
import java.util.concurrent.ExecutionException;

public class StoreFetchDeleteTest
{

```
private final Converter<RiakObject> domainObjectConverter = new PassThroughConverter();
private static RiakCluster cluster;
private ByteArrayWrapper bucket = ByteArrayWrapper.create("bucket");

@BeforeClass
public static void setup() throws UnknownHostException
{
    RiakNode node = new RiakNode.Builder()
        .withRemoteAddress("localhost")
        .withRemotePort(8087)
        .build();

    cluster = RiakCluster.builder(node).build();
    cluster.start();
}

@AfterClass
public static void teardown()
{
    cluster.stop();
}

@Test
public void testStoreFetchDelete() throws ExecutionException, InterruptedException
{

    RiakObject o = RiakObject.create(bucket.unsafeGetValue()).setValue("test value");
    StoreMeta storeMeta = new StoreMeta.Builder().returnBody(true).build();

    StoreOperation<RiakObject> store =
        new StoreOperation<RiakObject>(bucket, o)
            .withConverter(domainObjectConverter)
            .withStoreMeta(storeMeta);

    cluster.execute(store);

    RiakObject storeReturn = store.get();

    ByteArrayWrapper returnedKey = ByteArrayWrapper.create(storeReturn.getBucketAsBytes());
    FetchOperation<RiakObject> fetch =
        new FetchOperation<RiakObject>(bucket, returnedKey)
        .withConverter(domainObjectConverter);

    cluster.execute(fetch);

    RiakObject fetchReturn = fetch.get();

    DeleteOperation delete = new DeleteOperation(bucket, returnedKey);

    cluster.execute(delete);

    delete.get();

    FetchOperation<RiakObject> tombstoneFetch =
        new FetchOperation<RiakObject>(bucket, returnedKey)
        .withConverter(domainObjectConverter);

    cluster.execute(tombstoneFetch);

    RiakObject tombstone = tombstoneFetch.get();

    Assert.assertTrue(tombstone.isNotFound());

}

@Test
public void testSiblings() throws ExecutionException, InterruptedException
{

    RiakObject o = RiakObject.create(bucket.unsafeGetValue()).setValue("test value");
    StoreMeta storeMeta = new StoreMeta.Builder().returnBody(true).build();

    StoreOperation<RiakObject> store1 =
        new StoreOperation<RiakObject>(bucket, o)
            .withConverter(domainObjectConverter)
            .withStoreMeta(storeMeta);

    cluster.execute(store1);

    RiakObject storeReturn1 = store1.get();

    ByteArrayWrapper key = ByteArrayWrapper.create(storeReturn1.getKeyAsBytes());
    StoreOperation<RiakObject> store2 =
        new StoreOperation<RiakObject>(bucket, key, o)
            .withConverter(domainObjectConverter)
            .withStoreMeta(storeMeta);

    cluster.execute(store2);

    RiakObject storeReturn2 = store2.get();


}
```

}

Why version 2.0 code test programer use lib  1.4.4 api?????????????
It's joke!!!!!

**Comment by molele2** [comment]
so All version is eable to used!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by molele2** [comment]
the url http://docs.basho.com/riak/latest/dev/using/search/#Why-Riak-Search is fine for use success!
The riak is very joke!!!!!!!!!!!!!!

**Comment by molele2** [comment]
经过我一个月左右时间的尝试,我决定放弃riak了,给出的文档文章一片乱,上面标注着2.0.5的版本,但是例子中错误百出,甚至从github上下载的2.0的java库,中带着1.4.4的代码,之后整个test工程下全是一堆没用的代码,形如:

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

/**
- Unit test for simple App.
  _/
  public class AppTest 
  extends TestCase
  {
  /_*
  - Create the test case
    *
  - @param testName name of the test case
    */
    public AppTest( String testName )
    {
    super( testName );
    }
  
  /**
  - @return the suite of tests being tested
    */
    public static Test suite()
    {
    return new TestSuite( AppTest.class );
    }
  
  /**
  - Rigourous Test :-)
    */
    public void testApp()
    {
    assertTrue( true );
    }
    }

不知道形如这样的继承类用来干嘛?

代码中没有一个看起来能够在2.0.5下面正确使用的lib,我觉得白白浪费了一个月时间在riak上,还不知道这个万亿能干吗

说实话现在到处都是kv,实在让人不知道kv干嘛用,而且leveldb也是kv,riak也是kv,mongodb是kv,reids是kv,memcached是kv,kv有几何,郁闷了,我醉了

**Comment by molele2** [comment]
kv加油

**Comment by molele2** [comment]
经过一番挣扎之后我决定放弃riak这个东西太不靠普了

**Comment by molele2** [comment]
bye riak!!!!!!!!

**Comment by molele2** [comment]
key-value 存储系统 RocksDB
轻量级Key-value存储 iPage
key-value 存储系统 Keyspace
key-value 数据存储 OpenKeyval
Key-Value数据引擎 quickdb
分布式 key-value 存储系统 Scalaris
key-value存储系统 kvs
key-value 存储服务器 QDBM
加密的 key-value 存储系统 Trousseau
Key-Value 数据库 GT.M

Python实现的Key-Value数据库 spugdb

分布式的Key-Value存储系统 Kai
分布式的Key-Value存储系统 Ringo
Key-Value数据库 Flare
分布式的Key-Value存储系统 Dynomite
key-value 存储服务器 LightCloud
key-value 存储服务器 Riak

分布式的Key-Value存储系统 ThruDB
基于内存的数据库系统 VoltDB
K/V存储数据库 TreapDB
K/V存储方案 TomP2P

**Comment by molele2** [comment]
so many kv
kv
kv
kv ........................
oh,my god,我醉了，怪不得我写了n多年技术之后，越来越不喜欢，这些长着技术样，个个都说自己是kv的家伙，一点营养价值都没有，而且个个都说自己很好很牛皮，我以为是从火星来的技术，kv
kv，我又醉了

**Comment by kesslerm** [comment]
Dear @molele2,

running your latest message through google translator suggest that you were severely inebriated writing this. I will close this bug report. Please come back once you are able to formulate your thoughts in a clearer manner.
